Adds Localization into the whole backend.
Techtimize/sunndio-backend pull request #4
Opened 2023-02-10 09:51 UTC by masadmunawar

Adds Localization into the whole backend. and updates the APIs names by adding country Code

2023-02-10 14:25 UTC, anees-rehman-techtimize commented on src/routers/daignonsisResult.js
> +      if (req.params.countryCode == "es") {
define an Enum for Country code, and use the enum key in If conditions. avoid the hardcoded string "es" and "en"

2023-02-10 14:27 UTC, anees-rehman-techtimize commented on src/routers/daignonsisResult.js
> +        resultPercentage.push(obj);
Code is duplicated in if and else block, create the obj before if, and add the obj in resultPercentage at the end of IF condition

2023-02-13 16:29 UTC, anees-rehman-techtimize requested changes
Please create an Enum for country codes and use it in If conditions. Also try to minimize the code duplication in each if-else code blocks.

2023-02-15 11:08 UTC, masadmunawar commented on src/routers/daignonsisResult.js
> +      if (req.params.countryCode == "es") {
Done

2023-02-15 11:08 UTC, masadmunawar commented on src/routers/daignonsisResult.js
> +        resultPercentage.push(obj);
Done

2023-02-15 15:12 UTC, anees-rehman-techtimize approved these changes

2023-02-15 15:13 UTC, merged