Feature/error handling
Techtimize/sunndio-backend pull request #5
Opened 2023-02-13 09:57 UTC by masadmunawar

Adds error Handling on Backend side via JSON file

2023-02-17 07:00 UTC, anees-rehman-techtimize commented on src/routers/daignonsisResult.js
> +        const errorMessage = errorMessageEs.INVALID_COUNTRY_CODE;
Here, how do you know that country code is "ES" and you are getting the error message in Spanish?

2023-02-17 07:20 UTC, anees-rehman-techtimize commented on src/routers/daignonsisResult.js
> +      req.params.countryCode === "es"
Check country code from Enum file

2023-02-17 07:20 UTC, anees-rehman-techtimize commented on src/routers/daignonsisResult.js
> +        const errorMessage = errorMessageEs.INVALID_COUNTRY_CODE;
Return EN message by default.

2023-02-17 07:21 UTC, anees-rehman-techtimize commented on src/routers/daignonsisResult.js
> +      } else if (req.params.countryCode == CountryCode.ENGLISH) {
Add a new country code "en-us" and before checking the code, convert it to lowercase.

2023-02-17 07:23 UTC, anees-rehman-techtimize commented on src/routers/daignonsisResult.js
>  router.get("/calculateDiagnotics/:countryCode", async (req, res) => {
it should be POST request

2023-02-17 07:24 UTC, anees-rehman-techtimize commented on src/routers/daignonsisResult.js
>      res.status(200).send(resultPercentage);
Return only top 3 diagnosis in ascending order of percentage.

2023-02-17 07:24 UTC, anees-rehman-techtimize requested changes
please make the required changes

2023-02-17 11:31 UTC, masadmunawar commented on src/routers/daignonsisResult.js
> +        const errorMessage = errorMessageEs.INVALID_COUNTRY_CODE;
done

2023-02-17 11:31 UTC, masadmunawar commented on src/routers/daignonsisResult.js
> +      } else if (req.params.countryCode == CountryCode.ENGLISH) {
done

2023-02-17 11:31 UTC, masadmunawar commented on src/routers/daignonsisResult.js
> +      req.params.countryCode === "es"
done

2023-02-17 12:37 UTC, masadmunawar commented on src/routers/daignonsisResult.js
>  router.get("/calculateDiagnotics/:countryCode", async (req, res) => {
done

2023-02-18 08:27 UTC, anees-rehman-techtimize approved these changes

2023-02-18 08:28 UTC, merged